[package]
name = "now_importer_binary"
version = "0.2.0"
authors = ["Mike Engel <mike@mike-engel.com>"]
edition = "2018"

[dependencies]
now_importer = { path = "../now_importer" }
log = "0.4"
simplelog = "0.5"
clap = "2"
dirs = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
